name: workflow

on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # run every Monday

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml

    - name: Test notebooks
      run: python -m pytest -v --nbval --sanitize-with nbval.cfg examples/*.ipynb demo2.ipynb # examples/*.ipynb getting-started/*.ipynb
